/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ActivitiesRouteRouteImport } from './routes/activities/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as ActivitiesNewRouteImport } from './routes/activities/new'
import { Route as ActivitiesActivityIdRouteRouteImport } from './routes/activities/$activityId/route'
import { Route as SettingsCategoriesIndexRouteImport } from './routes/settings/categories/index'
import { Route as ActivitiesActivityIdIndexRouteImport } from './routes/activities/$activityId/index'
import { Route as ActivitiesActivityIdEditRouteImport } from './routes/activities/$activityId/edit'
import { Route as ActivitiesActivityIdDeleteRouteImport } from './routes/activities/$activityId/delete'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRouteRoute = ActivitiesRouteRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActivitiesRouteRoute,
} as any)
const ActivitiesActivityIdRouteRoute =
  ActivitiesActivityIdRouteRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => ActivitiesRouteRoute,
  } as any)
const SettingsCategoriesIndexRoute = SettingsCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ActivitiesActivityIdIndexRoute =
  ActivitiesActivityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ActivitiesActivityIdRouteRoute,
  } as any)
const ActivitiesActivityIdEditRoute =
  ActivitiesActivityIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ActivitiesActivityIdRouteRoute,
  } as any)
const ActivitiesActivityIdDeleteRoute =
  ActivitiesActivityIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ActivitiesActivityIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/history': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/activities/$activityId/delete': typeof ActivitiesActivityIdDeleteRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
  '/activities/$activityId/': typeof ActivitiesActivityIdIndexRoute
  '/settings/categories': typeof SettingsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/history': typeof HistoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/activities/$activityId/delete': typeof ActivitiesActivityIdDeleteRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
  '/activities/$activityId': typeof ActivitiesActivityIdIndexRoute
  '/settings/categories': typeof SettingsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRoute
  '/activities': typeof ActivitiesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRouteRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/history/': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/activities/$activityId/delete': typeof ActivitiesActivityIdDeleteRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
  '/activities/$activityId/': typeof ActivitiesActivityIdIndexRoute
  '/settings/categories/': typeof SettingsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/settings'
    | '/login'
    | '/activities/$activityId'
    | '/activities/new'
    | '/demo/tanstack-query'
    | '/settings/account'
    | '/settings/notifications'
    | '/history'
    | '/settings/'
    | '/activities/$activityId/delete'
    | '/activities/$activityId/edit'
    | '/activities/$activityId/'
    | '/settings/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/login'
    | '/activities/new'
    | '/demo/tanstack-query'
    | '/settings/account'
    | '/settings/notifications'
    | '/history'
    | '/settings'
    | '/activities/$activityId/delete'
    | '/activities/$activityId/edit'
    | '/activities/$activityId'
    | '/settings/categories'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/activities'
    | '/settings'
    | '/login'
    | '/activities/$activityId'
    | '/activities/new'
    | '/demo/tanstack-query'
    | '/settings/account'
    | '/settings/notifications'
    | '/history/'
    | '/settings/'
    | '/activities/$activityId/delete'
    | '/activities/$activityId/edit'
    | '/activities/$activityId/'
    | '/settings/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRoute
  ActivitiesRouteRoute: typeof ActivitiesRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof ActivitiesRouteRoute
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteRouteImport
      parentRoute: typeof ActivitiesRouteRoute
    }
    '/settings/categories/': {
      id: '/settings/categories/'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/activities/$activityId/': {
      id: '/activities/$activityId/'
      path: '/'
      fullPath: '/activities/$activityId/'
      preLoaderRoute: typeof ActivitiesActivityIdIndexRouteImport
      parentRoute: typeof ActivitiesActivityIdRouteRoute
    }
    '/activities/$activityId/edit': {
      id: '/activities/$activityId/edit'
      path: '/edit'
      fullPath: '/activities/$activityId/edit'
      preLoaderRoute: typeof ActivitiesActivityIdEditRouteImport
      parentRoute: typeof ActivitiesActivityIdRouteRoute
    }
    '/activities/$activityId/delete': {
      id: '/activities/$activityId/delete'
      path: '/delete'
      fullPath: '/activities/$activityId/delete'
      preLoaderRoute: typeof ActivitiesActivityIdDeleteRouteImport
      parentRoute: typeof ActivitiesActivityIdRouteRoute
    }
  }
}

interface ActivitiesActivityIdRouteRouteChildren {
  ActivitiesActivityIdDeleteRoute: typeof ActivitiesActivityIdDeleteRoute
  ActivitiesActivityIdEditRoute: typeof ActivitiesActivityIdEditRoute
  ActivitiesActivityIdIndexRoute: typeof ActivitiesActivityIdIndexRoute
}

const ActivitiesActivityIdRouteRouteChildren: ActivitiesActivityIdRouteRouteChildren =
  {
    ActivitiesActivityIdDeleteRoute: ActivitiesActivityIdDeleteRoute,
    ActivitiesActivityIdEditRoute: ActivitiesActivityIdEditRoute,
    ActivitiesActivityIdIndexRoute: ActivitiesActivityIdIndexRoute,
  }

const ActivitiesActivityIdRouteRouteWithChildren =
  ActivitiesActivityIdRouteRoute._addFileChildren(
    ActivitiesActivityIdRouteRouteChildren,
  )

interface ActivitiesRouteRouteChildren {
  ActivitiesActivityIdRouteRoute: typeof ActivitiesActivityIdRouteRouteWithChildren
  ActivitiesNewRoute: typeof ActivitiesNewRoute
}

const ActivitiesRouteRouteChildren: ActivitiesRouteRouteChildren = {
  ActivitiesActivityIdRouteRoute: ActivitiesActivityIdRouteRouteWithChildren,
  ActivitiesNewRoute: ActivitiesNewRoute,
}

const ActivitiesRouteRouteWithChildren = ActivitiesRouteRoute._addFileChildren(
  ActivitiesRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsCategoriesIndexRoute: typeof SettingsCategoriesIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsCategoriesIndexRoute: SettingsCategoriesIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRoute,
  ActivitiesRouteRoute: ActivitiesRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
